FROM golang:1.17-alpine3.15

ENV PYTHONUNBUFFERED=1

RUN apk update &&\
    apk upgrade &&\
    apk add make gcc g++ python3 &&\
    ln -sf python3 /usr/bin/python &&\
    python3 -m ensurepip &&\
    pip3 install --no-cache --upgrade pip setuptools
