# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dec < Formula
  desc "Create python or go development environment. dec create python app or de create go app"
  homepage "https://github.com/emylincon/dec"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/emylincon/dec/releases/download/v0.0.2/dec_0.0.2_Darwin_x86_64.tar.gz"
      sha256 "d86ac295b1541a6d6caebf83b50c693a44654dd676b3a17c68b4ac661f125bb5"

      def install
        bin.install "dec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/emylincon/dec/releases/download/v0.0.2/dec_0.0.2_Darwin_arm64.tar.gz"
      sha256 "5b1545b91e888c6feed93c2390f6c7139f7bf9538e4b31e744e2ff4aebd68572"

      def install
        bin.install "dec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/emylincon/dec/releases/download/v0.0.2/dec_0.0.2_Linux_x86_64.tar.gz"
      sha256 "c16a18967322afb41148ed4b8166d7e4ed4bcff927934e1105daf4132bca6699"

      def install
        bin.install "dec"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/emylincon/dec/releases/download/v0.0.2/dec_0.0.2_Linux_arm64.tar.gz"
      sha256 "ebeb7e7456ec2f06edd39e2472763f7982e34e67411c3b337fcf50db22e03439"

      def install
        bin.install "dec"
      end
    end
  end
end
